name: UnityBuild

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  editorTestJob:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2018.4.12f1]

    steps:
    - uses: actions/checkout@master
    - run: openssl aes-256-cbc -d -in Unity_v2018.x.ulf-cipher -k ${CYPHER_KEY} >> /Unity_v2018.x.ulf
      env:
        CYPHER_KEY: ${{ secrets.cypherkey }}
    - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile /Unity_v2018.x.ulf || exit 0
    - run: |
          CURRENT_DIR=`pwd`
          echo ${CURRENT_DIR}
          /opt/Unity/Editor/Unity -batchmode -quit -logFile ./build.log -projectPath GithubActions -executeMethod BuildClass.Build /output_path artifact || exit 0
    - uses: actions/upload-artifact@master
      with:
        name: WebGLBuild
        path: WebGL