name: UnityBuild

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  editorTestJob:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:2018.4.12f1-webgl

    steps:
    - uses: actions/checkout@main
    - run: openssl aes-256-cbc -d -in Unity_v2018.x.ulf-cipher -k ${CYPHER_KEY} -md md5 >> /Unity_v2018.x.ulf
      env:
        CYPHER_KEY: ${{ secrets.CYPHERKEY }}
    - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile /Unity_v2018.x.ulf || exit 0
    - run: mkdir artifact
    - run: /opt/Unity/Editor/Unity -batchmode -noGraphics -quit -silent-crashes -logFile artifact/build.log -buildTarget WebGL -projectPath Project -executeMethod BuildClass.Build /output_path ../artifact || exit 0
    - uses: actions/upload-artifact@main
      with:
        name: WebGLBuild
        path: artifact